services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./webapp:/usr/share/nginx/html/webapp

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command:
      - --provider=oidc
      - --provider-display-name=Keycloak
      - --client-id=webapp-client
      - --client-secret=oauth2-proxy-secret
      - --code-challenge-method=S256
      - --oidc-extra-audience=webapp-client
      - --oidc-issuer-url=http://keycloak:8080/keycloak/realms/example
      - --redirect-url=http://localhost:8000/oauth2/callback
      - --upstream=http://nginx:8000/webapp-internal/
      - --http-address=0.0.0.0:4180
      - --cookie-secret=0123456789abcdef0123456789abcdef
      - --email-domain=*
      - --skip-provider-button=true
    ports:
      - "4180:4180"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=keycloak
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=test
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    ports:
      - "8080:8080"
